# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Bill Liu
tagline:          'Blogs'
url:              http://bupt075225.github.io
paginate:         1
baseurl:          http://bupt075225.github.io
encoding:         utf-8
author:
  name:           Bill Liu
  url:            https://twitter.com/bupt075225
  email:          nonprivatemail@163.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/bupt075225/bupt075225.github.io.git
  
# This is the list of pages to include in the header of the website.
pages_list:        {'About':' http://bupt075225.github.io/about','Archive':' http://bupt075225.github.io/archive'}
